// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shapers.People.Infrastructure;

#nullable disable

namespace Shapers.People.Infrastructure.Migrations
{
    [DbContext(typeof(PeopleDbContext))]
    partial class PeopleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("people")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shapers.People.Domain.ConnectCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("HandledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("handled_at");

                    b.Property<Guid?>("HandledByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("handled_by_user_id");

                    b.Property<string>("HandlerNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("handler_note");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string[]>("Reasons")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("reasons");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("scope");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id")
                        .HasName("pk_connect_cards");

                    b.HasIndex("Scope")
                        .HasDatabaseName("ix_connect_cards_scope");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Scope"), new[] { "text_pattern_ops" });

                    b.HasIndex("Status", "SubmittedAt")
                        .HasDatabaseName("ix_connect_cards_status_submitted_at");

                    b.ToTable("connect_cards", "people");
                });

            modelBuilder.Entity("Shapers.People.Domain.ConsentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Granted")
                        .HasColumnType("boolean")
                        .HasColumnName("granted");

                    b.Property<string>("LawfulBasis")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("lawful_basis");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("policy_version");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("purpose");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid?>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_consent_records");

                    b.HasIndex("PersonId", "Purpose", "RecordedAt")
                        .HasDatabaseName("ix_consent_records_person_id_purpose_recorded_at");

                    b.ToTable("consent_records", "people");
                });

            modelBuilder.Entity("Shapers.People.Domain.DuplicateCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<Guid>("PersonAId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_a_id");

                    b.Property<Guid>("PersonBId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_b_id");

                    b.Property<string>("Reasons")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reasons");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_duplicate_candidates");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_duplicate_candidates_status");

                    b.HasIndex("PersonAId", "PersonBId")
                        .IsUnique()
                        .HasDatabaseName("ix_duplicate_candidates_person_a_id_person_b_id");

                    b.ToTable("duplicate_candidates", "people");
                });

            modelBuilder.Entity("Shapers.People.Domain.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("PrimaryContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_contact_id");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("scope");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_households");

                    b.HasIndex("Scope")
                        .HasDatabaseName("ix_households_scope");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Scope"), new[] { "text_pattern_ops" });

                    b.ToTable("households", "people");
                });

            modelBuilder.Entity("Shapers.People.Domain.MembershipStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stage");

                    b.HasKey("Id")
                        .HasName("pk_membership_statuses");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ix_membership_statuses_is_default")
                        .HasFilter("is_default");

                    b.ToTable("membership_statuses", "people");
                });

            modelBuilder.Entity("Shapers.People.Domain.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<Guid>("MembershipStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_status_id");

                    b.Property<Guid?>("MergedIntoId")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_into_id");

                    b.Property<string>("PreferredName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("preferred_name");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("scope");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_persons");

                    b.HasIndex("MembershipStatusId")
                        .HasDatabaseName("ix_persons_membership_status_id");

                    b.HasIndex("MergedIntoId")
                        .HasDatabaseName("ix_persons_merged_into_id");

                    b.HasIndex("Scope")
                        .HasDatabaseName("ix_persons_scope");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Scope"), new[] { "text_pattern_ops" });

                    b.HasIndex("LastName", "FirstName")
                        .HasDatabaseName("ix_persons_last_name_first_name");

                    b.ToTable("persons", "people");
                });

            modelBuilder.Entity("Shapers.People.Domain.PersonMerge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("MergedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("merged_at");

                    b.Property<Guid?>("MergedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_by_user_id");

                    b.Property<Guid>("MergedId")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_id");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot");

                    b.Property<Guid>("SurvivorId")
                        .HasColumnType("uuid")
                        .HasColumnName("survivor_id");

                    b.HasKey("Id")
                        .HasName("pk_person_merges");

                    b.HasIndex("MergedId")
                        .HasDatabaseName("ix_person_merges_merged_id");

                    b.HasIndex("SurvivorId")
                        .HasDatabaseName("ix_person_merges_survivor_id");

                    b.ToTable("person_merges", "people");
                });

            modelBuilder.Entity("Shapers.Platform.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_occurred_at")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", "people");
                });

            modelBuilder.Entity("Shapers.People.Domain.Household", b =>
                {
                    b.OwnsMany("Shapers.People.Domain.HouseholdMember", "Members", b1 =>
                        {
                            b1.Property<Guid>("HouseholdId")
                                .HasColumnType("uuid")
                                .HasColumnName("household_id");

                            b1.Property<Guid>("PersonId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("person_id");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("role");

                            b1.HasKey("HouseholdId", "PersonId")
                                .HasName("pk_household_members");

                            b1.HasIndex("PersonId")
                                .HasDatabaseName("ix_household_members_person_id");

                            b1.ToTable("household_members", "people");

                            b1.WithOwner()
                                .HasForeignKey("HouseholdId")
                                .HasConstraintName("fk_household_members_households_household_id");
                        });

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Shapers.People.Domain.Person", b =>
                {
                    b.HasOne("Shapers.People.Domain.MembershipStatus", null)
                        .WithMany()
                        .HasForeignKey("MembershipStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_persons_membership_statuses_membership_status_id");

                    b.OwnsMany("Shapers.People.Domain.ContactPoint", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean")
                                .HasColumnName("is_primary");

                            b1.Property<bool>("IsVerified")
                                .HasColumnType("boolean")
                                .HasColumnName("is_verified");

                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid")
                                .HasColumnName("person_id");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("type");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("character varying(254)")
                                .HasColumnName("value");

                            b1.HasKey("Id")
                                .HasName("pk_person_contacts");

                            b1.HasIndex("PersonId")
                                .HasDatabaseName("ix_person_contacts_person_id");

                            b1.HasIndex("Value")
                                .HasDatabaseName("ix_person_contacts_value");

                            b1.ToTable("person_contacts", "people");

                            b1.WithOwner()
                                .HasForeignKey("PersonId")
                                .HasConstraintName("fk_person_contacts_persons_person_id");
                        });

                    b.OwnsMany("Shapers.People.Domain.MembershipStatusChange", "StatusHistory", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid?>("ChangedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("changed_by_user_id");

                            b1.Property<DateOnly>("EffectiveDate")
                                .HasColumnType("date")
                                .HasColumnName("effective_date");

                            b1.Property<Guid?>("FromStatusId")
                                .HasColumnType("uuid")
                                .HasColumnName("from_status_id");

                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid")
                                .HasColumnName("person_id");

                            b1.Property<DateTimeOffset>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<Guid>("ToStatusId")
                                .HasColumnType("uuid")
                                .HasColumnName("to_status_id");

                            b1.HasKey("Id")
                                .HasName("pk_membership_status_changes");

                            b1.HasIndex("PersonId")
                                .HasDatabaseName("ix_membership_status_changes_person_id");

                            b1.ToTable("membership_status_changes", "people");

                            b1.WithOwner()
                                .HasForeignKey("PersonId")
                                .HasConstraintName("fk_membership_status_changes_persons_person_id");
                        });

                    b.Navigation("Contacts");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
