<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Shapers.Identity.Domain/Shapers.Identity.Domain.csproj" />
    <ProjectReference Include="../Shapers.Identity.Contracts/Shapers.Identity.Contracts.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Shapers.Platform/Shapers.Platform.csproj" />
    <ProjectReference Include="../../People/Shapers.People.Contracts/Shapers.People.Contracts.csproj" />
    <ProjectReference Include="../../Church/Shapers.Church.Contracts/Shapers.Church.Contracts.csproj" />
    <ProjectReference Include="../../Media/Shapers.Media.Contracts/Shapers.Media.Contracts.csproj" />
    <ProjectReference Include="../../Events/Shapers.Events.Contracts/Shapers.Events.Contracts.csproj" />
    <ProjectReference Include="../../Prayer/Shapers.Prayer.Contracts/Shapers.Prayer.Contracts.csproj" />
    <ProjectReference Include="../../Communications/Shapers.Communications.Contracts/Shapers.Communications.Contracts.csproj" />
    <ProjectReference Include="../../Privacy/Shapers.Privacy.Contracts/Shapers.Privacy.Contracts.csproj" />
    <ProjectReference Include="../../Content/Shapers.Content.Contracts/Shapers.Content.Contracts.csproj" />
    <ProjectReference Include="../../Groups/Shapers.Groups.Contracts/Shapers.Groups.Contracts.csproj" />
    <ProjectReference Include="../../Assist/Shapers.Assist.Contracts/Shapers.Assist.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Shapers.Identity.Tests" />
  </ItemGroup>
</Project>
