<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Shapers.Groups.Domain/Shapers.Groups.Domain.csproj" />
    <ProjectReference Include="../Shapers.Groups.Contracts/Shapers.Groups.Contracts.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Shapers.Platform/Shapers.Platform.csproj" />
    <ProjectReference Include="../../People/Shapers.People.Contracts/Shapers.People.Contracts.csproj" />
    <ProjectReference Include="../../Church/Shapers.Church.Contracts/Shapers.Church.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Shapers.Groups.Tests" />
  </ItemGroup>
</Project>
