<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Shapers.Communications.Application/Shapers.Communications.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="EFCore.NamingConventions" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Shapers.Communications.Tests" />
    <InternalsVisibleTo Include="Shapers.IntegrationTests" />
  </ItemGroup>
</Project>
