// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shapers.Communications.Infrastructure;

#nullable disable

namespace Shapers.Communications.Infrastructure.Migrations
{
    [DbContext(typeof(CommunicationsDbContext))]
    [Migration("20260930091806_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("communications")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shapers.Communications.Domain.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<string>("DisabledReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("disabled_reason");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_devices_person_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_token");

                    b.ToTable("devices", "communications");
                });

            modelBuilder.Entity("Shapers.Communications.Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Link")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("link");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_key");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("topic");

                    b.Property<bool>("Urgent")
                        .HasColumnType("boolean")
                        .HasColumnName("urgent");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("PersonId", "CreatedAt")
                        .HasDatabaseName("ix_notifications_person_id_created_at");

                    b.HasIndex("PersonId", "SourceKey")
                        .IsUnique()
                        .HasDatabaseName("ix_notifications_person_id_source_key");

                    b.ToTable("notifications", "communications");
                });

            modelBuilder.Entity("Shapers.Communications.Domain.TopicPreference", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Topic")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("topic");

                    b.Property<string>("Channel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PersonId", "Topic", "Channel")
                        .HasName("pk_preferences");

                    b.ToTable("preferences", "communications");
                });

            modelBuilder.Entity("Shapers.Platform.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_occurred_at")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", "communications");
                });

            modelBuilder.Entity("Shapers.Communications.Domain.Notification", b =>
                {
                    b.OwnsMany("Shapers.Communications.Domain.Delivery", "Deliveries", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Attempts")
                                .HasColumnType("integer")
                                .HasColumnName("attempts");

                            b1.Property<string>("Channel")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("channel");

                            b1.Property<string>("Error")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("error");

                            b1.Property<DateTimeOffset>("NotBefore")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("not_before");

                            b1.Property<Guid>("NotificationId")
                                .HasColumnType("uuid")
                                .HasColumnName("notification_id");

                            b1.Property<string>("ProviderReference")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("provider_reference");

                            b1.Property<DateTimeOffset?>("SentAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("sent_at");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("status");

                            b1.HasKey("Id")
                                .HasName("pk_deliveries");

                            b1.HasIndex("NotificationId")
                                .HasDatabaseName("ix_deliveries_notification_id");

                            b1.HasIndex("Status", "NotBefore")
                                .HasDatabaseName("ix_deliveries_status_not_before");

                            b1.ToTable("deliveries", "communications");

                            b1.WithOwner()
                                .HasForeignKey("NotificationId")
                                .HasConstraintName("fk_deliveries_notifications_notification_id");
                        });

                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
