// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shapers.Groups.Infrastructure;

#nullable disable

namespace Shapers.Groups.Infrastructure.Migrations
{
    [DbContext(typeof(GroupsDbContext))]
    partial class GroupsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("groups")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shapers.Groups.Domain.Cell", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<string>("Area")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("area");

                    b.Property<Guid>("CampusId")
                        .HasColumnType("uuid")
                        .HasColumnName("campus_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MeetingDay")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("meeting_day");

                    b.Property<TimeOnly?>("MeetingTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("meeting_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("scope");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_cells");

                    b.HasIndex("Scope")
                        .HasDatabaseName("ix_cells_scope");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Scope"), new[] { "text_pattern_ops" });

                    b.ToTable("cells", "groups");
                });

            modelBuilder.Entity("Shapers.Groups.Domain.CellMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("body");

                    b.Property<Guid>("CellId")
                        .HasColumnType("uuid")
                        .HasColumnName("cell_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("ForDate")
                        .HasColumnType("date")
                        .HasColumnName("for_date");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("link");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("scope");

                    b.Property<bool>("SharedWithMembers")
                        .HasColumnType("boolean")
                        .HasColumnName("shared_with_members");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WrittenByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("written_by_person_id");

                    b.HasKey("Id")
                        .HasName("pk_materials");

                    b.HasIndex("Scope")
                        .HasDatabaseName("ix_materials_scope");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Scope"), new[] { "text_pattern_ops" });

                    b.HasIndex("CellId", "UpdatedAt")
                        .HasDatabaseName("ix_materials_cell_id_updated_at");

                    b.ToTable("materials", "groups");
                });

            modelBuilder.Entity("Shapers.Groups.Domain.CellMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CellId")
                        .HasColumnType("uuid")
                        .HasColumnName("cell_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_members_person_id");

                    b.HasIndex("CellId", "PersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_members_cell_id_person_id")
                        .HasFilter("left_at IS NULL");

                    b.ToTable("members", "groups");
                });

            modelBuilder.Entity("Shapers.Groups.Domain.CellReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<Guid>>("AttendeeIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("attendee_ids");

                    b.Property<Guid>("CellId")
                        .HasColumnType("uuid")
                        .HasColumnName("cell_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FollowUps")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("follow_ups");

                    b.Property<string>("Growth")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("growth");

                    b.Property<string>("Highlights")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("highlights");

                    b.Property<Guid?>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<DateOnly>("MeetingDate")
                        .HasColumnType("date")
                        .HasColumnName("meeting_date");

                    b.Property<int>("MembersPresent")
                        .HasColumnType("integer")
                        .HasColumnName("members_present");

                    b.Property<string>("Multiplication")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("multiplication");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<string>("PrayerNeeds")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("prayer_needs");

                    b.Property<DateTimeOffset?>("RedactedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redacted_at");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("scope");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("Topic")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("topic");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VisitorCount")
                        .HasColumnType("integer")
                        .HasColumnName("visitor_count");

                    b.Property<string>("Visitors")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("visitors");

                    b.Property<Guid>("WrittenByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("written_by_person_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("Scope")
                        .HasDatabaseName("ix_reports_scope");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Scope"), new[] { "text_pattern_ops" });

                    b.HasIndex("CellId", "MeetingDate")
                        .IsUnique()
                        .HasDatabaseName("ix_reports_cell_id_meeting_date");

                    b.HasIndex("RedactedAt", "MeetingDate")
                        .HasDatabaseName("ix_reports_redacted_at_meeting_date");

                    b.ToTable("reports", "groups");
                });

            modelBuilder.Entity("Shapers.Platform.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_occurred_at")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", "groups");
                });

            modelBuilder.Entity("Shapers.Groups.Domain.CellMember", b =>
                {
                    b.HasOne("Shapers.Groups.Domain.Cell", null)
                        .WithMany("Members")
                        .HasForeignKey("CellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_members_cells_cell_id");
                });

            modelBuilder.Entity("Shapers.Groups.Domain.Cell", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
