// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shapers.Services.Infrastructure;

#nullable disable

namespace Shapers.Services.Infrastructure.Migrations
{
    [DbContext(typeof(ServicesDbContext))]
    [Migration("20261006110211_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("services")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shapers.Platform.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_occurred_at")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", "services");
                });

            modelBuilder.Entity("Shapers.Services.Domain.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("DeclineReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("decline_reason");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<DateTimeOffset?>("RemindedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reminded_at");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("scope");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_assignments");

                    b.HasIndex("Date", "Status")
                        .HasDatabaseName("ix_assignments_date_status");

                    b.HasIndex("PersonId", "Date")
                        .HasDatabaseName("ix_assignments_person_id_date");

                    b.HasIndex("PlanId", "PositionId", "PersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_assignments_plan_id_position_id_person_id");

                    b.ToTable("assignments", "services");
                });

            modelBuilder.Entity("Shapers.Services.Domain.Blockout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date")
                        .HasColumnName("from");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.Property<DateOnly>("To")
                        .HasColumnType("date")
                        .HasColumnName("to");

                    b.HasKey("Id")
                        .HasName("pk_blockouts");

                    b.HasIndex("PersonId", "To")
                        .HasDatabaseName("ix_blockouts_person_id_to");

                    b.ToTable("blockouts", "services");
                });

            modelBuilder.Entity("Shapers.Services.Domain.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("items");

                    b.Property<DateTimeOffset?>("LiveEndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("live_ended_at");

                    b.Property<Guid?>("LiveItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("live_item_id");

                    b.Property<DateTimeOffset?>("LiveItemStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("live_item_started_at");

                    b.Property<Guid?>("LivestreamId")
                        .HasColumnType("uuid")
                        .HasColumnName("livestream_id");

                    b.Property<string>("Needs")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("needs");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("scope");

                    b.Property<string>("SeriesTitle")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("series_title");

                    b.Property<Guid?>("ServiceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_type_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_plans");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_plans_date");

                    b.HasIndex("Scope")
                        .HasDatabaseName("ix_plans_scope");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Scope"), new[] { "text_pattern_ops" });

                    b.ToTable("plans", "services");
                });

            modelBuilder.Entity("Shapers.Services.Domain.ServiceType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("items");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("Needs")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("needs");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("scope");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_service_types");

                    b.ToTable("service_types", "services");
                });

            modelBuilder.Entity("Shapers.Services.Domain.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Arrangements")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("arrangements");

                    b.Property<string>("Author")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("author");

                    b.Property<string>("CcliNumber")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("ccli_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Lyrics")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("lyrics");

                    b.Property<string>("ReferenceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reference_url");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("scope");

                    b.PrimitiveCollection<List<string>>("Themes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("themes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_songs");

                    b.HasIndex("CcliNumber")
                        .HasDatabaseName("ix_songs_ccli_number");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_songs_title");

                    b.ToTable("songs", "services");
                });

            modelBuilder.Entity("Shapers.Services.Domain.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<bool>("OpenToMinors")
                        .HasColumnType("boolean")
                        .HasColumnName("open_to_minors");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("scope");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("Scope")
                        .HasDatabaseName("ix_teams_scope");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Scope"), new[] { "text_pattern_ops" });

                    b.ToTable("teams", "services");
                });

            modelBuilder.Entity("Shapers.Services.Domain.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<bool>("IsLeader")
                        .HasColumnType("boolean")
                        .HasColumnName("is_leader");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.PrimitiveCollection<List<Guid>>("PositionIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("position_ids");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_members_person_id");

                    b.HasIndex("TeamId", "PersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_members_team_id_person_id");

                    b.ToTable("members", "services");
                });

            modelBuilder.Entity("Shapers.Services.Domain.TeamPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_positions_team_id");

                    b.ToTable("positions", "services");
                });
#pragma warning restore 612, 618
        }
    }
}
