// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Shapers.Media.Infrastructure;

#nullable disable

namespace Shapers.Media.Infrastructure.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    partial class MediaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("media")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shapers.Media.Domain.Livestream", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CurrentCueId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_cue_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("GiveUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("give_url");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("ScheduledStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_start");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("scope");

                    b.Property<Guid?>("SermonId")
                        .HasColumnType("uuid")
                        .HasColumnName("sermon_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_livestreams");

                    b.HasIndex("Status", "ScheduledStart")
                        .HasDatabaseName("ix_livestreams_status_scheduled_start");

                    b.ToTable("livestreams", "media");
                });

            modelBuilder.Entity("Shapers.Media.Domain.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("original_file_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("storage_key");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ix_assets_storage_key");

                    b.ToTable("assets", "media");
                });

            modelBuilder.Entity("Shapers.Media.Domain.PlaybackPosition", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("SermonId")
                        .HasColumnType("uuid")
                        .HasColumnName("sermon_id");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean")
                        .HasColumnName("completed");

                    b.Property<int>("PositionSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("position_seconds");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PersonId", "SermonId")
                        .HasName("pk_playback_positions");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_playback_positions_updated_at");

                    b.ToTable("playback_positions", "media");
                });

            modelBuilder.Entity("Shapers.Media.Domain.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArtworkAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("artwork_asset_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("scope");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateOnly?>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_series");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_series_slug");

                    b.ToTable("series", "media");
                });

            modelBuilder.Entity("Shapers.Media.Domain.Sermon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AudioAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("audio_asset_id");

                    b.Property<int?>("AudioDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("audio_duration_seconds");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImportSource")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("import_source");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("NotesPdfAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("notes_pdf_asset_id");

                    b.Property<DateOnly>("PreachedOn")
                        .HasColumnType("date")
                        .HasColumnName("preached_on");

                    b.Property<DateTimeOffset?>("PublishAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publish_at");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("scope");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_text");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('english', coalesce(search_text, ''))", true);

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.PrimitiveCollection<List<string>>("Topics")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("topics");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_sermons");

                    b.HasIndex("ImportSource")
                        .IsUnique()
                        .HasDatabaseName("ix_sermons_import_source")
                        .HasFilter("import_source IS NOT NULL");

                    b.HasIndex("Scope")
                        .HasDatabaseName("ix_sermons_scope");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Scope"), new[] { "text_pattern_ops" });

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_sermons_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_sermons_series_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_sermons_slug");

                    b.HasIndex("Topics")
                        .HasDatabaseName("ix_sermons_topics");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Topics"), "gin");

                    b.HasIndex("Status", "PreachedOn")
                        .HasDatabaseName("ix_sermons_status_preached_on");

                    b.ToTable("sermons", "media");
                });

            modelBuilder.Entity("Shapers.Media.Domain.Speaker", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("bio");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid?>("PhotoAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_asset_id");

                    b.Property<string>("Title")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_speakers");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_speakers_name");

                    b.ToTable("speakers", "media");
                });

            modelBuilder.Entity("Shapers.Platform.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_occurred_at")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", "media");
                });

            modelBuilder.Entity("Shapers.Media.Domain.Livestream", b =>
                {
                    b.OwnsOne("Shapers.Media.Domain.VideoLink", "Video", b1 =>
                        {
                            b1.Property<Guid>("LivestreamId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ExternalId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("video_external_id");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("video_provider");

                            b1.HasKey("LivestreamId");

                            b1.ToTable("livestreams", "media");

                            b1.WithOwner()
                                .HasForeignKey("LivestreamId")
                                .HasConstraintName("fk_livestreams_livestreams_id");
                        });

                    b.OwnsMany("Shapers.Media.Domain.ScriptureCue", "Cues", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("LivestreamId")
                                .HasColumnType("uuid")
                                .HasColumnName("livestream_id");

                            b1.Property<int>("Order")
                                .HasColumnType("integer")
                                .HasColumnName("order");

                            b1.Property<string>("Reference")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("reference");

                            b1.Property<DateTimeOffset?>("ShownAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("shown_at");

                            b1.Property<string>("Text")
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)")
                                .HasColumnName("text");

                            b1.HasKey("Id")
                                .HasName("pk_livestream_cues");

                            b1.HasIndex("LivestreamId")
                                .HasDatabaseName("ix_livestream_cues_livestream_id");

                            b1.ToTable("livestream_cues", "media");

                            b1.WithOwner()
                                .HasForeignKey("LivestreamId")
                                .HasConstraintName("fk_livestream_cues_livestreams_livestream_id");
                        });

                    b.Navigation("Cues");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Shapers.Media.Domain.Sermon", b =>
                {
                    b.OwnsMany("Shapers.Media.Domain.ScriptureReference", "Scripture", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b1.Property<int>("Id"));

                            b1.Property<int>("BookNumber")
                                .HasColumnType("integer")
                                .HasColumnName("book_number");

                            b1.Property<int>("ChapterFrom")
                                .HasColumnType("integer")
                                .HasColumnName("chapter_from");

                            b1.Property<int>("ChapterTo")
                                .HasColumnType("integer")
                                .HasColumnName("chapter_to");

                            b1.Property<Guid>("SermonId")
                                .HasColumnType("uuid")
                                .HasColumnName("sermon_id");

                            b1.Property<int?>("VerseFrom")
                                .HasColumnType("integer")
                                .HasColumnName("verse_from");

                            b1.Property<int?>("VerseTo")
                                .HasColumnType("integer")
                                .HasColumnName("verse_to");

                            b1.HasKey("Id")
                                .HasName("pk_sermon_scripture");

                            b1.HasIndex("BookNumber")
                                .HasDatabaseName("ix_sermon_scripture_book_number");

                            b1.HasIndex("SermonId")
                                .HasDatabaseName("ix_sermon_scripture_sermon_id");

                            b1.ToTable("sermon_scripture", "media");

                            b1.WithOwner()
                                .HasForeignKey("SermonId")
                                .HasConstraintName("fk_sermon_scripture_sermons_sermon_id");
                        });

                    b.OwnsOne("Shapers.Media.Domain.VideoLink", "Video", b1 =>
                        {
                            b1.Property<Guid>("SermonId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ExternalId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("video_external_id");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("video_provider");

                            b1.HasKey("SermonId");

                            b1.ToTable("sermons", "media");

                            b1.WithOwner()
                                .HasForeignKey("SermonId")
                                .HasConstraintName("fk_sermons_sermons_id");
                        });

                    b.OwnsMany("Shapers.Media.Domain.SermonSpeaker", "Speakers", b1 =>
                        {
                            b1.Property<Guid>("SermonId")
                                .HasColumnType("uuid")
                                .HasColumnName("sermon_id");

                            b1.Property<Guid>("SpeakerId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("speaker_id");

                            b1.Property<int>("Order")
                                .HasColumnType("integer")
                                .HasColumnName("order");

                            b1.HasKey("SermonId", "SpeakerId")
                                .HasName("pk_sermon_speakers");

                            b1.HasIndex("SpeakerId")
                                .HasDatabaseName("ix_sermon_speakers_speaker_id");

                            b1.ToTable("sermon_speakers", "media");

                            b1.WithOwner()
                                .HasForeignKey("SermonId")
                                .HasConstraintName("fk_sermon_speakers_sermons_sermon_id");
                        });

                    b.Navigation("Scripture");

                    b.Navigation("Speakers");

                    b.Navigation("Video");
                });
#pragma warning restore 612, 618
        }
    }
}
