/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/church": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetChurch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListAuditEntries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/scopes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListScopes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/campuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListCampuses"];
        put?: never;
        post: operations["CreateCampus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/campuses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["UpdateCampus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/ministries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListMinistries"];
        put?: never;
        post: operations["CreateMinistry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListPeople"];
        put?: never;
        post: operations["CreatePerson"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/people/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetPerson"];
        put: operations["UpdatePerson"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/people/{id}/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AddPersonContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/people/{id}/contacts/{contactId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["RemovePersonContact"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/people/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ChangeMembershipStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/people/{id}/campus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MovePersonCampus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/people/{id}/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RecordPersonConsent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/people/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MergePeople"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/duplicates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListDuplicates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/duplicates/{id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DismissDuplicate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/households/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetHousehold"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/households": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CreateHousehold"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/households/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AddHouseholdMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/households/{id}/members/{personId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["RemoveHouseholdMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/households/{id}/primary-contact/{personId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SetHouseholdPrimaryContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/membership-statuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListMembershipStatuses"];
        put?: never;
        post: operations["CreateMembershipStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetMyProfile"];
        put: operations["UpdateMyProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RecordMyConsent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RequestSignInCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["VerifySignInCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RefreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/staff/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StaffLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/staff/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StaffLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/staff/set-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SetStaffPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/2fa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetTwoFactorStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/2fa/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SetupAuthenticator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/2fa/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EnableTwoFactor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetMyAccess"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["SetMyPreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListRoles"];
        put?: never;
        post: operations["CreateRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["UpdateRole"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/people/{personId}/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetPersonAccess"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/people/{personId}/staff-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PrepareStaffLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CreateGrant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/grants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["RevokeGrant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddContactRequest: {
            type: components["schemas"]["ContactType"];
            value: string;
            isPrimary: boolean;
        };
        AddressDto: {
            line1: string;
            line2: null | string;
            suburb: null | string;
            city: string;
            province: string;
            postalCode: string;
            /** @default ZA */
            countryCode: string;
        };
        AuditEntryDto: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            occurredAt: string;
            /** Format: uuid */
            actorUserId: null | string;
            /** Format: uuid */
            actorPersonId: null | string;
            action: string;
            entityType: string;
            entityId: null | string;
            scope: null | string;
            isSensitiveRead: boolean;
            ipAddress: null | string;
        };
        AuthenticatorSetup: {
            sharedKey: string;
            authenticatorUri: string;
        };
        CampusDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            scope: string;
            address: null | components["schemas"]["AddressDto"];
            status: string;
            isPrimary: boolean;
        };
        /** @enum {unknown} */
        CampusStatus: "Planned" | "Active" | "Closed";
        ChangeStatusRequest: {
            /** Format: uuid */
            membershipStatusId: string;
            /** Format: date */
            effectiveDate: null | string;
        };
        ChurchOverviewDto: {
            organisation: components["schemas"]["OrganisationDto"];
            campuses: components["schemas"]["CampusDto"][];
        };
        ConsentDecision: {
            purpose: string;
            granted: boolean;
        };
        ConsentDecisionDto: {
            purpose: string;
            granted: boolean;
        };
        ConsentDto: {
            purpose: string;
            granted: boolean;
            lawfulBasis: components["schemas"]["LawfulBasis"];
            policyVersion: string;
            source: components["schemas"]["ConsentSource"];
            /** Format: date-time */
            recordedAt: string;
        };
        /** @enum {unknown} */
        ConsentSource: "MobileApp" | "Website" | "AdminPortal" | "PaperForm" | "Import";
        ContactDto: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["ContactType"];
            value: string;
            isPrimary: boolean;
            isVerified: boolean;
        };
        /** @enum {unknown} */
        ContactType: "Email" | "Mobile" | "WhatsApp";
        CreateCampusRequest: {
            name: string;
            slug: string;
            address: null | components["schemas"]["AddressDto"];
        };
        CreateGrantRequest: {
            /** Format: uuid */
            personId: string;
            /** Format: uuid */
            roleId: string;
            scope: string;
            /** Format: date-time */
            expiresAt: null | string;
            reason: null | string;
        };
        CreateHouseholdRequest: {
            name: string;
            /** Format: uuid */
            campusId: null | string;
            members: components["schemas"]["HouseholdMemberRequest"][];
        };
        CreateMembershipStatusRequest: {
            name: string;
            stage: components["schemas"]["JourneyStage"];
            /** Format: int32 */
            sortOrder: number;
        };
        CreateMinistryRequest: {
            name: string;
            slug: string;
            /** Format: uuid */
            campusId: null | string;
        };
        CreatePersonRequest: {
            firstName: string;
            lastName: string;
            preferredName: null | string;
            /** Format: date */
            dateOfBirth: null | string;
            gender: null | components["schemas"]["Gender"];
            /** Format: uuid */
            campusId: null | string;
            /** Format: uuid */
            membershipStatusId: null | string;
            email: null | string;
            mobile: null | string;
        };
        DuplicateCandidateDto: {
            /** Format: uuid */
            id: string;
            personA: components["schemas"]["PersonListItemDto"];
            personB: components["schemas"]["PersonListItemDto"];
            /** Format: int32 */
            score: number;
            reasons: string;
            /** Format: date-time */
            detectedAt: string;
        };
        EnableTwoFactorRequest: {
            code: string;
        };
        /** @enum {unknown} */
        Gender: "Female" | "Male" | null;
        GrantDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            roleId: string;
            roleName: string;
            scope: string;
            /** Format: date-time */
            grantedAt: string;
            /** Format: date-time */
            expiresAt: null | string;
            reason: null | string;
            isActive: boolean;
        };
        HouseholdDto: {
            /** Format: uuid */
            id: string;
            name: string;
            scope: string;
            members: components["schemas"]["HouseholdMemberDto"][];
        };
        HouseholdMemberDto: {
            /** Format: uuid */
            personId: string;
            displayName: string;
            role: components["schemas"]["HouseholdRole"];
            isPrimaryContact: boolean;
        };
        HouseholdMemberRequest: {
            /** Format: uuid */
            personId: string;
            role: components["schemas"]["HouseholdRole"];
        };
        /** @enum {unknown} */
        HouseholdRole: "Adult" | "Child";
        /** @enum {unknown} */
        JourneyStage: "Visitor" | "Regular" | "GrowthTrack" | "Member" | "Inactive";
        /** @enum {unknown} */
        LawfulBasis: "Consent" | "LegitimateInterest" | "LegalObligation" | "Contract";
        LogoutRequest: {
            refreshToken: string;
        };
        MembershipStatusDto: {
            /** Format: uuid */
            id: string;
            name: string;
            stage: components["schemas"]["JourneyStage"];
            /** Format: int32 */
            sortOrder: number;
            isDefault: boolean;
            isActive: boolean;
        };
        MergeRequest: {
            /** Format: uuid */
            survivorId: string;
            /** Format: uuid */
            duplicateId: string;
        };
        MinistryDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            scope: string;
            /** Format: uuid */
            campusId: null | string;
            isActive: boolean;
        };
        MoveCampusRequest: {
            /** Format: uuid */
            campusId: string;
        };
        MyAccessDto: {
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            personId: string;
            displayName: string;
            hasMfa: boolean;
            twoFactorEnabled: boolean;
            mfaRequiredForSensitive: boolean;
            palette: string;
            permissions: components["schemas"]["PermissionScopesDto"][];
        };
        OrganisationDto: {
            /** Format: uuid */
            id: string;
            name: string;
            legalName: null | string;
            scope: string;
            timeZone: string;
            currency: string;
            contactEmail: null | string;
            website: null | string;
            isSection18AApproved: boolean;
        };
        PagedResultOfAuditEntryDto: {
            items: components["schemas"]["AuditEntryDto"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            total: number;
        };
        PagedResultOfPersonListItemDto: {
            items: components["schemas"]["PersonListItemDto"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            total: number;
        };
        PermissionDto: {
            key: string;
            module: string;
            description: string;
            isSensitive: boolean;
        };
        PermissionScopesDto: {
            permission: string;
            scopes: string[];
        };
        PersonAccessDto: {
            /** Format: uuid */
            personId: string;
            /** Format: uuid */
            userId: null | string;
            email: null | string;
            phone: null | string;
            twoFactorEnabled: boolean;
            hasPassword: boolean;
            /** Format: date-time */
            lastSignInAt: null | string;
            grants: components["schemas"]["GrantDto"][];
        };
        PersonDetailDto: {
            /** Format: uuid */
            id: string;
            firstName: string;
            lastName: string;
            preferredName: null | string;
            displayName: string;
            /** Format: date */
            dateOfBirth: null | string;
            gender: null | components["schemas"]["Gender"];
            scope: string;
            campusName: null | string;
            membershipStatus: components["schemas"]["MembershipStatusDto"];
            status: components["schemas"]["PersonStatus"];
            /** Format: uuid */
            mergedIntoId: null | string;
            source: components["schemas"]["PersonSource"];
            hasLogin: boolean;
            contacts: components["schemas"]["ContactDto"][];
            households: components["schemas"]["HouseholdDto"][];
            statusHistory: components["schemas"]["StatusChangeDto"][];
            consents: components["schemas"]["ConsentDto"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PersonListItemDto: {
            /** Format: uuid */
            id: string;
            displayName: string;
            firstName: string;
            lastName: string;
            scope: string;
            campusName: null | string;
            membershipStatus: string;
            stage: string;
            status: string;
            primaryEmail: null | string;
            primaryMobile: null | string;
        };
        /** @enum {unknown} */
        PersonSource: "Admin" | "SelfRegistration" | "VisitorCard" | "EventRegistration" | "Giving" | "Import";
        /** @enum {unknown} */
        PersonStatus: "Active" | "Inactive" | "Deceased" | "Merged";
        PreferencesRequest: {
            palette: string;
        };
        RecordConsentRequest: {
            decisions: components["schemas"]["ConsentDecisionDto"][];
            policyVersion: string;
            source: components["schemas"]["ConsentSource"];
            lawfulBasis?: components["schemas"]["LawfulBasis"];
        };
        RecoveryCodes: {
            codes: string[];
        };
        RefreshRequest: {
            refreshToken: string;
            device: null | string;
        };
        RegisterRequest: {
            /** Format: uuid */
            challengeId: string;
            registrationTicket: string;
            firstName: string;
            lastName: string;
            email: null | string;
            /** Format: uuid */
            campusId: null | string;
            policyVersion: string;
            consents: components["schemas"]["ConsentDecision"][];
            device: null | string;
        };
        RequestCodeRequest: {
            phone: string;
        };
        RequestCodeResponse: {
            /** Format: uuid */
            challengeId: string;
            /** Format: date-time */
            expiresAt: string;
            maskedPhone: string;
        };
        RoleDto: {
            /** Format: uuid */
            id: string;
            name: string;
            description: null | string;
            isSystem: boolean;
            permissions: string[];
        };
        SaveRoleRequest: {
            name: string;
            description: null | string;
            permissions: string[];
        };
        ScopeSummary: {
            path: string;
            name: string;
            type: string;
            /** Format: uuid */
            entityId: null | string;
        };
        SetPasswordRequest: {
            /** Format: uuid */
            userId: string;
            token: string;
            password: string;
        };
        SignInResponse: {
            status: components["schemas"]["SignInStatus"];
            tokens: null | components["schemas"]["TokenPair"];
            registrationTicket: null | string;
            existingRecordFound: boolean;
        };
        /** @enum {unknown} */
        SignInStatus: "SignedIn" | "RegistrationRequired";
        StaffLoginRequestDto: {
            email: string;
        };
        StaffLoginResponse: {
            status: components["schemas"]["StaffLoginStatus"];
        };
        StaffLoginSetupDto: {
            /** Format: uuid */
            userId: string;
            email: string;
            setupToken: string;
        };
        /** @enum {unknown} */
        StaffLoginStatus: "SignedIn" | "TwoFactorRequired";
        StaffSignInRequest: {
            email: string;
            password: string;
            twoFactorCode: null | string;
            recoveryCode: null | string;
        };
        StatusChangeDto: {
            from: null | string;
            to: string;
            /** Format: date */
            effectiveDate: string;
            /** Format: date-time */
            recordedAt: string;
        };
        TokenPair: {
            accessToken: string;
            /** Format: date-time */
            accessTokenExpiresAt: string;
            refreshToken: string;
            /** Format: date-time */
            refreshTokenExpiresAt: string;
        };
        TwoFactorStatus: {
            enabled: boolean;
            /** Format: int32 */
            recoveryCodesLeft: number;
        };
        UpdateCampusRequest: {
            name: string;
            address: null | components["schemas"]["AddressDto"];
            status: components["schemas"]["CampusStatus"];
        };
        UpdateMyProfileRequest: {
            firstName: string;
            lastName: string;
            preferredName: null | string;
            /** Format: date */
            dateOfBirth: null | string;
        };
        UpdatePersonRequest: {
            firstName: string;
            lastName: string;
            preferredName: null | string;
            /** Format: date */
            dateOfBirth: null | string;
            gender: null | components["schemas"]["Gender"];
        };
        VerifyCodeRequest: {
            /** Format: uuid */
            challengeId: string;
            code: string;
            device: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetChurch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChurchOverviewDto"];
                };
            };
        };
    };
    ListAuditEntries: {
        parameters: {
            query?: {
                entityType?: string;
                entityId?: string;
                actorUserId?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfAuditEntryDto"];
                };
            };
        };
    };
    ListScopes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScopeSummary"][];
                };
            };
        };
    };
    ListCampuses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampusDto"][];
                };
            };
        };
    };
    CreateCampus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCampusRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampusDto"];
                };
            };
        };
    };
    UpdateCampus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCampusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampusDto"];
                };
            };
        };
    };
    ListMinistries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MinistryDto"][];
                };
            };
        };
    };
    CreateMinistry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMinistryRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MinistryDto"];
                };
            };
        };
    };
    ListPeople: {
        parameters: {
            query?: {
                Search?: string;
                Scope?: string;
                MembershipStatusId?: string;
                IncludeInactive?: boolean;
                Page?: number;
                PageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfPersonListItemDto"];
                };
            };
        };
    };
    CreatePerson: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePersonRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetailDto"];
                };
            };
        };
    };
    GetPerson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetailDto"];
                };
            };
        };
    };
    UpdatePerson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePersonRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetailDto"];
                };
            };
        };
    };
    AddPersonContact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddContactRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetailDto"];
                };
            };
        };
    };
    RemovePersonContact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                contactId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetailDto"];
                };
            };
        };
    };
    ChangeMembershipStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetailDto"];
                };
            };
        };
    };
    MovePersonCampus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveCampusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetailDto"];
                };
            };
        };
    };
    RecordPersonConsent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordConsentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentDto"][];
                };
            };
        };
    };
    MergePeople: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetailDto"];
                };
            };
        };
    };
    ListDuplicates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateCandidateDto"][];
                };
            };
        };
    };
    DismissDuplicate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetHousehold: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdDto"];
                };
            };
        };
    };
    CreateHousehold: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHouseholdRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdDto"];
                };
            };
        };
    };
    AddHouseholdMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HouseholdMemberRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdDto"];
                };
            };
        };
    };
    RemoveHouseholdMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                personId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdDto"];
                };
            };
        };
    };
    SetHouseholdPrimaryContact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                personId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdDto"];
                };
            };
        };
    };
    ListMembershipStatuses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipStatusDto"][];
                };
            };
        };
    };
    CreateMembershipStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMembershipStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipStatusDto"];
                };
            };
        };
    };
    GetMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetailDto"];
                };
            };
        };
    };
    UpdateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMyProfileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetailDto"];
                };
            };
        };
    };
    RecordMyConsent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordConsentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentDto"][];
                };
            };
        };
    };
    RequestSignInCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCodeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestCodeResponse"];
                };
            };
        };
    };
    VerifySignInCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyCodeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInResponse"];
                };
            };
        };
    };
    Register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInResponse"];
                };
            };
        };
    };
    RefreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
        };
    };
    Logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StaffLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffSignInRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffLoginResponse"];
                };
            };
        };
    };
    StaffLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SetStaffPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPasswordRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetTwoFactorStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TwoFactorStatus"];
                };
            };
        };
    };
    SetupAuthenticator: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatorSetup"];
                };
            };
        };
    };
    EnableTwoFactor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnableTwoFactorRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryCodes"];
                };
            };
        };
    };
    GetMyAccess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyAccessDto"];
                };
            };
        };
    };
    SetMyPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionDto"][];
                };
            };
        };
    };
    ListRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDto"][];
                };
            };
        };
    };
    CreateRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveRoleRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDto"];
                };
            };
        };
    };
    UpdateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveRoleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDto"];
                };
            };
        };
    };
    GetPersonAccess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                personId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonAccessDto"];
                };
            };
        };
    };
    PrepareStaffLogin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                personId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffLoginRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffLoginSetupDto"];
                };
            };
        };
    };
    CreateGrant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGrantRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantDto"];
                };
            };
        };
    };
    RevokeGrant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
